# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('nicknames', models.TextField(null=True)),
                ('definition', models.TextField(null=True)),
                ('organism_short', models.CharField(max_length=16)),
                ('organism', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=16)),
                ('ntseq_length', models.IntegerField()),
                ('ntseq', models.TextField(null=True)),
            ],
            options={
                'db_table': 'bio_gene',
            },
        ),
        migrations.CreateModel(
            name='Gene_Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=64)),
                ('disease_name', models.CharField(max_length=64)),
                ('disease_class', models.CharField(max_length=64)),
                ('paper_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bio_gene_disease',
            },
        ),
        migrations.CreateModel(
            name='One_KeySentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name_one', models.CharField(max_length=64)),
                ('gene_name_two', models.CharField(max_length=64)),
                ('sentence', models.TextField()),
            ],
            options={
                'db_table': 'bio_one_keysentence',
            },
        ),
        migrations.CreateModel(
            name='Paper_Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=32)),
                ('paper_title', models.CharField(max_length=255)),
                ('paper_keyword', models.CharField(default=None, max_length=255)),
                ('paper_abstract', models.TextField()),
                ('paper_link', models.CharField(max_length=255)),
                ('paper_class', models.IntegerField(default=-1)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneRelationship.Gene')),
            ],
            options={
                'db_table': 'bio_paper_gene',
            },
        ),
        migrations.CreateModel(
            name='Three_KeySentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name_one', models.CharField(max_length=64)),
                ('gene_name_two', models.CharField(max_length=64)),
                ('sentence', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneRelationship.Paper_Gene')),
            ],
            options={
                'db_table': 'bio_three_keysentence',
            },
        ),
        migrations.AddField(
            model_name='one_keysentence',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneRelationship.Paper_Gene'),
        ),
    ]
